### Import Libraries

In [7]:
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
import re
import pandas as pd
from sqlalchemy import create_engine
import lxml
import os
import time

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

### Test for 200 Response

In [8]:
url = 'https://www.aliexpress.com/w/wholesale-laptop.html?page=1&g=y&SearchText=laptop'
response = requests.get(url)
print(response)

<Response [200]>

### Configure Selenium

In [9]:
# Configure Selenium chrome Driver options
options = Options()
options.headless = True
service = Service(executable_path = r'chromedriver-win64\chromedriver.exe')

# Initialize the webdriver
driver = webdriver.Chrome(service = service, options = options)

# Define the URL
url = 'https://www.aliexpress.com/w/wholesale-laptop.html?page=1&g=y&SearchText=laptop'

# Use selenium to open the page and wait for dynamic content to load
time.sleep(10)

# Get the page source code and close the browser
page_source = driver.page_source
driver.quit()

#### Running Some selenium tests

In [11]:
# Configure Selenium chrome Driver options
options = Options()
options.headless = True
service = Service(executable_path = r'chromedriver-win64\chromedriver.exe')

# Initialize the webdriver
driver = webdriver.Chrome(service = service, options = options)

url = f'https://www.aliexpress.com/w/wholesale-laptop.html?page={1}&g=y&SearchText=laptop'
driver.get(url)
time.sleep(5)

# Now we use Beautifulsoup to parse the loaded page_source
soup = BeautifulSoup(driver.page_source, 'html.parser')

product_name = soup.find('h3', class_ = 'multi--titleText--nXeOvyr').text

product_name2 = soup.find('div', class_ = 'multi--title--G7dOCj3').text

                
price = soup.find('div', class_ ='multi--price-sale--U-S0jtj')

data = soup.find(string = re.compile('NGN'))

store_name = soup.find('a', class_ ='cards--storeLink--XkKUQFS').text


#Store link
try:
    Store_link = soup.find('a', class_ ='cards--storeLink--XknnKUQFS')['href']

# except TypeError as e:
#     Store_link = ''
#     print(f"TypeError occurred: {e}")

except KeyError as e:
    Store_link = ''
    print(f"KeyError occurred: {e}")
    
except Exception as e:
    Store_link = ''
    print(f"Error Type: {type(e)}")        # Error class
    print(f"Error Arguments: {e.args}")    # Error message and details

# Shipping free statuses
try:
    shipping_free_statuses = soup.find('span', class_ = 'tag--text--1BSEXVh tag--textStyle--3dc7wLU multi--serviceStyle--1Z6RxQ4').text
    shipping_free_statuses1 = soup.find('div', class_ = 'multi--serviceContainer--3vRdzWN').text

except Exception as e:
    shipping_free_statuses1 = ''
    shipping_free_statuses = ''
    print(f"Error Type: {type(e)}")        # Error class
    print(f"Error Arguments: {e.args}")    # Error message and details


# Original_prices
try:
    original_price = soup.find('div', class_ = 'multi--price-original--1zEQqOK').text
    old_price = original_price.strip() if original_price else ''

except Exception as e:
    original_price = ''
    print(f"Error Type for original_price: {type(e)}")        # Error class
    print(f"Error Arguments for original_price: {e.args}")    # Error message and details

        
# Shipping free statuses
try:
    shipping_statuses = soup.find('div', class_ = 'multi--serviceContainer--3vRdzWN').text
    ship_status = shipping_statuses.strip() if shipping_statuses else ''

except Exception as e:
    shipping_statuses = ''
    print(f"Error Type for shipping_statuses: {type(e)}")        # Error class
    print(f"Error Arguments for shipping_statuses: {e.args}")    # Error message and details


# Item sold
try:
    item_sold = soup.find('span', class_ = 'multi--trade--Ktbl2jB').text
    item_sold_split = item_sold.split()[0] if item_sold else ''
        
except AttributeError as e:
     item_sold = ''
     print(f"KeyError occurred: {e}")

except Exception as e:
    item_sold = ''
    print(f"Error Type: {type(e)}")        # Error class
    print(f"Error Arguments: {e.args}")    # Error message and details


extra_discount = soup.find('span', class_ = 'tag--text--1BSEXVh tag--textStyle--3dc7wLU multi--superStyle--1jUmObG').text

shipping_price = soup.find('span', class_ = 'tag--text--1BSEXVh tag--textStyle--3dc7wLU multi--serviceStyle--1Z6RxQ4').text


price

Error Type: <class 'TypeError'>
Error Arguments: ("'NoneType' object is not subscriptable",)

<div class="multi--price-sale--U-S0jtj"><span style="font-size:12px;currency-symbol:NGN;show-decimal:true;decimal_point:.;symbol_position:left;comma_style:,">NGN</span><span style="font-size:24px;currency-symbol:NGN;show-decimal:true;decimal_point:.;symbol_position:left;comma_style:,">8</span><span style="font-size:12px;currency-symbol:NGN;show-decimal:true;decimal_point:.;symbol_position:left;comma_style:,">,</span><span style="font-size:24px;currency-symbol:NGN;show-decimal:true;decimal_point:.;symbol_position:left;comma_style:,">158</span><span style="font-size:12px;currency-symbol:NGN;show-decimal:true;decimal_point:.;symbol_position:left;comma_style:,">,</span><span style="font-size:24px;currency-symbol:NGN;show-decimal:true;decimal_point:.;symbol_position:left;comma_style:,">094</span><span style="font-size:12px;currency-symbol:NGN;show-decimal:true;decimal_point:.;symbol_position:left;comma_style:,">.</span><span style="font-size:12px;currency-symbol:NGN;show-decimal:true;decimal_point:.;symbol_position:left;comma_style:,">1</span></div>

In [12]:
print(product_name)

print('\n')

print(price.text.replace('NGN', '').replace(',', ''))

print('\n')

print(product_name2)

print('\n')

print(data)

print('\n')

print(store_name)

print('\n')

print(Store_link)

print('\n')

print(shipping_free_statuses1)

print('\n')

print(shipping_free_statuses)

print('\n')

print(f'ship_status {ship_status}')

print('\n')

print(f'shipping_statuses {shipping_statuses}')

print('\n')

print(f'old_price {old_price}')

print('\n')

print(f'original_price {original_price}')

print('\n')

print(f'item_sold_split {item_sold_split}')

print('\n')

print(f'item_sold {item_sold}')

print('\n')

print(f'shipping_price {shipping_price}')

print('\n')

print(f'extra_discount {extra_discount}')

Ｈigh-end Lenovo Yoga Air 14c 2022 Laptop With i7-1280P Xe Graphics LPDDR5 1TB SSD ThunderBolt 14 Inch 2880X1800 Touch Display


8158094.1


Ｈigh-end Lenovo Yoga Air 14c 2022 Laptop With i7-1280P Xe Graphics LPDDR5 1TB SSD ThunderBolt 14 Inch 2880X1800 Touch Display


NGN


HUWEI Factory Store





Free shipping


Free shipping


ship_status Free shipping


shipping_statuses Free shipping


old_price


original_price


item_sold_split 16


item_sold 16 sold


shipping_price Free shipping


extra_discount Extra 5% off with coins

### Extraction Layer

In [13]:
# Configure Selenium chrome Driver options
options = Options()
options.headless = True
service = Service(executable_path = r'chromedriver-win64\chromedriver.exe')

# Initialize the webdriver
driver = webdriver.Chrome(service = service, options = options)

# Lists to store extracted data
product_names = []
prices = []
store_names = []
store_links = [] 
shipping_prices = []
extra_discounts = []
items_sold = []
original_prices = []
shipping_free_statuses = []


# Scrapping the pages
total_pages = range(1, 2)

for page in total_pages:
    url = f'https://www.aliexpress.com/w/wholesale-laptop.html?page={page}&g=y&SearchText=laptop'
    driver.get(url)
    time.sleep(10)

    # Now we use Beautifulsoup to parse the loaded page_source
    soup = BeautifulSoup(driver.page_source, 'html.parser')

    # Adjust the class selectors based on the current website structure
    laptops = soup.find_all('div', class_ = 'list--gallery--C2f2tvm search-item-card-wrapper-gallery')

    for laptop in laptops:
        # Product_name
        product_name = laptop.find('h3', class_ ='multi--titleText--nXeOvyr').text
        

        # Price
        price = laptop.find('div', class_ ='multi--price-sale--U-S0jtj').text.replace('NGN', '').replace(',', '')

       
        # Store name
        store_n = laptop.find('a', class_ ='cards--storeLink--XkKUQFS')
        store_name = store_n.text if store_n else ''

        
        #Store link
        try:
            store_link = laptop.find('a', class_ ='cards--storeLink--XkKUQFS')['href']

        except KeyError as e:
            store_link = ''
            print(f"KeyError occurred in store_link: {e}")

        except Exception as e:
            store_link = ''
            print(f"Error Type in store_link: {type(e)}")        # Error class
            print(f"Error Arguments in store_link: {e.args}")    # Error message and details

        
        # Shipping price
        try:
            shipping_p = laptop.find('span', class_ = 'tag--text--1BSEXVh tag--textStyle--3dc7wLU multi--serviceStyle--1Z6RxQ4')
            shipping_price = shipping_p.text if shipping_p else ''
        except AttributeError as e:
            shipping_price = ''
            print(f"KeyError occurred in shipping_price: {e}")

        except Exception as e:
            shipping_price = ''
            print(f"Error Type in shipping_price: {type(e)}")        # Error class
            print(f"Error Arguments in shipping_price: {e.args}")    # Error message and details

        
        # Extra discount
        try:
            extra_dis = laptop.find('span', class_ = 'tag--text--1BSEXVh tag--textStyle--3dc7wLU multi--superStyle--1jUmObG')
            extra_discount = extra_dis.text if extra_dis else ''

        except AttributeError as e:
            extra_discount = ''
            print(f"KeyError occurred in extra_discount: {e}")
            
        except Exception as e:
            extra_discount = ''
            print(f"Error Type in extra_discount: {type(e)}")        # Error class
            print(f"Error Arguments in extra_discount: {e.args}")    # Error message and details

        
        # Item sold
        try:
            item_sold = laptop.find('span', class_ = 'multi--trade--Ktbl2jB')
            item_sold_split = item_sold.text.split()[0] if item_sold else ''
        
        except AttributeError as e:
            item_sold = ''
            print(f"KeyError occurred in item_sold: {e}")

        except Exception as e:
            item_sold = ''
            print(f"Error Type in item_sold: {type(e)}")        # Error class
            print(f"Error Arguments in item_sold: {e.args}")    # Error message and details

        
        # Original_prices
        try:
            original_price = laptop.find('div', class_ = 'multi--price-original--1zEQqOK')
            old_price = original_price.text.strip() if original_price else ''

        except Exception as e:
            original_price = ''
            print(f"Error Type in original_price: {type(e)}")        # Error class
            print(f"Error Arguments in original_price: {e.args}")    # Error message and details

        
        # Shipping free statuses
        try:
            shipping_statuses = laptop.find('div', class_ = 'multi--serviceContainer--3vRdzWN')
            ship_status = shipping_statuses.text.strip() if shipping_statuses else ''

        except Exception as e:
            shipping_statuses = ''
            print(f"Error Type in shipping_statuses: {type(e)}")        # Error class
            print(f"Error Arguments in shipping_statuses: {e.args}")    # Error message and details


        # Append data to list
        product_names.append(product_name)
        prices.append(price)
        store_names.append(store_name)
        store_links.append(store_link)
        shipping_prices.append(shipping_price)
        extra_discounts.append(extra_discount)
        items_sold.append(item_sold_split)
        original_prices.append(old_price)
        shipping_free_statuses.append(ship_status)


# Once all the pages information are extracted, quit the driver
driver.quit()

#### Create a dataframe

In [31]:
data = {
    'Product_name' : product_names,
    'Price' : prices,
    'Store_name' : store_names,
    'Store_link' : store_links,
    'Shipping_price' : shipping_prices,
    'Extra_discount' : extra_discounts,
    'Items_sold' : items_sold,
    'Original_price' : original_prices,
    'Shipping_free_statuse' : shipping_free_statuses
}

francine_df = pd.DataFrame(data)

In [32]:
francine_df

,Product_name,Price,Store_name,Store_link,Shipping_price,Extra_discount,Items_sold,Original_price,Shipping_free_statuse
0,Notebook 15.6 inch Laptop Windows 11 10 Pro 19...,331236.75,Baby Doing Buy Store,//www.aliexpress.com/store/5881464,,,399,,
1,Adreamer Laptop 13.3 Inch Portable Laptops Low...,340428.2,ADREAMER Global Store,//www.aliexpress.com/store/1102333380,,"Save NGN416,080.93",461,,
2,GMOLO 14inch Windows 10 Notebook Laptop 6GB RA...,250090.91,LAPTOP Shop Store,//www.aliexpress.com/store/316137,,,16,,
3,Global Version Original Xioami Pad 7S Pro Tabl...,178739.33,Shop1104055985 Store,//www.aliexpress.com/store/1104055985,Free shipping,Extra 5% off with coins,79,,Free shipping
4,BYONE 11.6 Inch Mini Laptop Intel Celeron N400...,253644.21,BYONE Official Store,//www.aliexpress.com/store/900254088,Free shipping,Extra 2% off with coins,77,,Free shipping
5,10.9 Inch Mini Laptop Intel N95 YOGA Touchscre...,496284.06,YSJMNPC Official Store,//www.aliexpress.com/store/1100370457,,,108,,
6,FIREBAT A14 Laptop Intel N5095 14.1 Inch 16GB ...,475439.21,Stone's Store,//www.aliexpress.com/store/1103573332,"Free shipping over NGN18,129.1",Extra 2% off with coins,354,"NGN970,285.81","Free shipping over NGN18,129.1"
7,2024 NEW Original MI Tablet 11inch Snapdrago 8...,178487.86,5G Tablets Mall Store,//www.aliexpress.com/store/1103542095,Free shipping,Extra 5% off with coins,69,,Free shipping
8,Big discount Notebook Windows 10 11 Ram 16GB ...,342023.56,Baby Doing Buy Store,//www.aliexpress.com/store/5881464,,,246,,

#### Saving the raw data

In [33]:
francine_df.to_csv('Aliexpresslaptops.csv', index=False)

In [34]:
francine_df.columns

Index(['Product_name', 'Price', 'Store_name', 'Store_link', 'Shipping_price',
       'Extra_discount', 'Items_sold', 'Original_price',
       'Shipping_free_statuse'],
      dtype='object')

### Data Transformation

###### Creating tables

In [35]:
# Product table
product_columns = ['Product_name', 'Price', 'Store_name', 'Store_link']
products_table = francine_df[product_columns].copy().drop_duplicates().reset_index(drop=True)

# Creating a product id using a dedicated numbering system
products_table['product_id'] = range(7, len(products_table) + 7) # Sequential numbering starting at 7
products_table = products_table[['product_id', 'Product_name', 'Price', 'Store_name', 'Store_link']]

products_table.head()

,product_id,Product_name,Price,Store_name,Store_link
0,7,Notebook 15.6 inch Laptop Windows 11 10 Pro 19...,331236.75,Baby Doing Buy Store,//www.aliexpress.com/store/5881464
1,8,Adreamer Laptop 13.3 Inch Portable Laptops Low...,340428.2,ADREAMER Global Store,//www.aliexpress.com/store/1102333380
2,9,GMOLO 14inch Windows 10 Notebook Laptop 6GB RA...,250090.91,LAPTOP Shop Store,//www.aliexpress.com/store/316137
3,10,Global Version Original Xioami Pad 7S Pro Tabl...,178739.33,Shop1104055985 Store,//www.aliexpress.com/store/1104055985
4,11,BYONE 11.6 Inch Mini Laptop Intel Celeron N400...,253644.21,BYONE Official Store,//www.aliexpress.com/store/900254088

In [50]:
# Discount table
discount_column = ['Original_price', 'Extra_discount']
discounts_table = francine_df[discount_column].copy().drop_duplicates().reset_index(drop=True)

# Adding the product_id from the products_table
to_join_product_id = products_table['product_id'].copy().reset_index(drop=True)
discounts_table['product_id'] = to_join_product_id

# Creating a discounts id using a dedicated numbering system
discounts_table['discount_id'] = range(44, len(discounts_table) + 44) # Sequential numbering starting at 44
discounts_table = discounts_table[['discount_id', 'product_id', 'Original_price', 'Extra_discount']]

# Removing currency symbols and commas then we convert to float
discounts_table['Original_price'] = discounts_table['Original_price'].str.replace('NGN', '').str.replace(',', '').str.extract(r'(\d+)').fillna(0).astype(float)
                                                                                               
# extract discount percent value and coin percent value as integer
discounts_table['Extra_discount'] = discounts_table['Extra_discount'].str.extract(r'(\d+)%').fillna(0).astype(float)



discounts_table

   discount_id  product_id  Original_price  Extra_discount
0           44           7             0.0             0.0
1           45           8             0.0             0.0
2           46           9             0.0             5.0
3           47          10             0.0             2.0
4           48          11        970285.0             2.0

In [66]:
# Sales table
sales_column = ['Items_sold']
sales_table = francine_df[sales_column].copy().drop_duplicates().reset_index(drop=True)

# Adding the product_id from the products_table
columns_to_join = products_table['product_id'].copy().reset_index(drop=True)
sales_table['product_id'] = columns_to_join


# Creating a Sales id using a dedicated numbering system
sales_table['sales_id'] = range(131, len(sales_table) + 131) # Sequential numbering starting at 131
sales_table = sales_table[['sales_id', 'product_id', 'Items_sold']]

sales_table

   sales_id  product_id Items_sold
0       131           7        399
1       132           8        461
2       133           9         16
3       134          10         79
4       135          11         77
5       136          12        108
6       137          13        354
7       138          14         69
8       139          15        246

In [69]:
# Shipping table
shipping_column = ['Shipping_price']
shipping_table = francine_df[shipping_column].copy().drop_duplicates().reset_index(drop=True)

# Adding the product_id from the products_table
joining_product_id = products_table['product_id'].copy().reset_index(drop=True)
shipping_table['product_id'] = joining_product_id

# Creating a Sales id using a dedicated numbering system
shipping_table['shipping_id'] = range(250, len(shipping_table) + 250) # Sequential numbering starting at 250
shipping_table = shipping_table[['shipping_id', 'product_id', 'Shipping_price']]

shipping_table.fillna({'Shipping_price' : 0.0}, inplace=True)

shipping_table

   shipping_id  product_id                  Shipping_price
0          250           7
1          251           8                   Free shipping
2          252           9  Free shipping over NGN18,129.1

### Saving the tables to CSV

In [70]:
products_table.to_csv('products_table.csv', index=False)
sales_table.to_csv('sales_table.csv', index=False)
discounts_table.to_csv('discounts_table.csv', index=False)
shipping_table.to_csv('shipping_table.csv', index=False)

### Loading Layer

In [72]:
# Load environment variables from the .env file
load_dotenv()

db_params = {
    'username' : os.getenv('DB_USER'),
    'password' : os.getenv('PASSWORD'),
    'host' : os.getenv('HOST'),
    'port': int(os.getenv('PORT')),  # Ensure PORT is an integer
    'database' : os.getenv('DATABASE')
}

# define the database connection url
db_url = f"postgresql://{db_params['username']}:{db_params['password']}@{db_params['host']}:{db_params['port']}/{db_params['database']}"


# create the database engine with the db url specified
engine = create_engine(db_url)

# connect to postgreSQL server
with engine.connect() as connection:
    # Create table and load the data
    products_table.to_sql('products_table', connection, index = False, if_exists = 'replace')
    discounts_table.to_sql('discounts_table', connection, index = False, if_exists = 'replace')
    sales_table.to_sql('sales_table', connection, index = False, if_exists = 'replace')
    shipping_table.to_sql('shipping_table', connection, index = False, if_exists = 'replace')

print('Database, table and data loaded successfully')

Database, table and data loaded successfully